spring.application.name=parkeyBack
#DB configuration:
spring.datasource.url=jdbc:mysql://localhost:3306/parkeydb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://ademselmani:uVzfKO6u4WUxnSfS@cluster0.2qiqr3m.mongodb.net/parkeydb?retryWrites=true&w=majority&appName=Cluster0

#Web Server (tomcat) configuration :
server.port=8080
